name: company_website

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install, build 
        run: |
          npm install
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}  
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }} 




  deploy:
        name: Deploy
        needs: [test]
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          
          - name: Add remote origin to Heroku
            run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          
          - name: Deploy code to heroku
            run: git push --force heroku main